<a href="https://colab.research.google.com/github/shrd2855/DSML-JUL-25-DAV/blob/main/My_Python_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hello world')

hello world


In [ ]:
a = "13.56"
print(float(a))

13.56


In [ ]:
print(24)

24


In [ ]:
print("54" + "23")

5423


In [ ]:
print("1" == 1)

False


In [ ]:
x = 2
if x==2:
    x = 3
x = 4
else:
    x = 5
print(x)

SyntaxError: invalid syntax (<ipython-input-1-f39cd7db9a9c>, line 5)

In [ ]:
print(True == 1)

True


In [ ]:
8*8*8

512

In [ ]:
3*3*3*3*3

243

Question:Take an input from the user for start and end values and print every third number

In [ ]:
start = int(input())
end = int(input())
while start <= end:
  print(start)
  start+=3

10
20
10
13
16
19


Question: Take an input from the user for start and end values. Print all even numbers between them.

In [ ]:
start = int(input())
end = int(input())
while start <= end:
  if start%2==0:
    print(start)
  start+=1

1
5
2
4


Print the Table of any number

In [ ]:
N = int(input("Please enter the number ="))
t = N
while t <= 10*N:
  print(t)
  t += N


Please enter the number =16
16
32
48
64
80
96
112
128
144
160


Homework : Enter the Table of N

In [ ]:
N = int(input("Enter the Table of : "))
i = 1
while i <= 10:
  print(N*i)
  i += 1

Enter the Table of : 2
2
4
6
8
10
12
14
16
18
20


Ask number of tables to write on seperate lines.

In [ ]:
Tables = int(input("How many times you want to ask: "))
t = 1
while t <= Tables:
  N = int(input("Enter the Table of: "))
  i = 1
  while i <= 10:
    print(N*i, end = " ")
    i += 1
  t += 1
  print('\n')

How many times you want to ask: 2
Enter the Table of: 3
3 6 9 12 15 18 21 24 27 30 

Enter the Table of: 5
5 10 15 20 25 30 35 40 45 50 



In [ ]:
14 % 5

4

In [ ]:
x = int(input())
y = int(input())
q = 0
r = 0
while x >= y:
    x -= y
    q += 1
print(q, x)

17
5
3 2


In [ ]:
N = int(input())
print(N%10,(N//10)%10,(N//100)%10,sep="")

456
654


In [ ]:
T = int(input())
for i in range(T):
  N = int(input())
  N = N//10
  print(N)

3
123
12
123
12
123
12


In [ ]:
T = int(input())
for i in range(T):
    N = int(input())
    rev = 0
    while N > 0:
        rev = rev*10 + N%10
        N = N//10
    print(rev)

2
1256
6521
56987
78965


In [ ]:
print('yes')

yes


In [ ]:
10%2

0

Problem Description

Take an integer N as input, print the corresponding Numeric Inverted Half Pyramid pattern for N.

For example if N = 4 then pattern will be like:
1 2 3 4
1 2 3
1 2
1

In [ ]:
N = int(input())
for i in range(0,N):
    for j in range(1,N-i+1):
        print(j,end=' ')
    print()

4
1 2 3 4 
1 2 3 
1 2 
1 


In [ ]:
"This_is_a_underscore_separated_string".split("_")

['This', 'is', 'a', 'underscore', 'separated', 'string']

In [ ]:
tax = .05*25000
tax

1250.0

In [ ]:
def sequence(n):
    for i in range(1,n+1):
        if i != n:
            print(i,end = " ")
        else:
            print(i)
    for j in range(n,0,-1):
        if j != 1:
            print(j,end = " ")
        else:
            print(j)

In [ ]:
sequence(5)

1 2 3 4 5
5 4 3 2 1


In [ ]:
x = 55
def hi():
  return x
x +=10
print(hi())

65


In [ ]:
print(hi())

65


In [ ]:
def star(n):
    '''input: n = An Integer value defines number of rows
       output: print the star pattern'''
    # YOUR CODE GOES HERE
    for i in range(n):
        print('*',end='')
    print()
    for j in range(n-3,0,-1):
        print('*'+(j)*" "+'*')
    print('*')

In [ ]:
star(8)

********
*     *
*    *
*   *
*  *
* *
*


Write a program to find the difference between the sum of all even elements and the sum of all odd elements from the given array, A.

In [ ]:
def even_odd(A):
    diff = 0
    even = 0
    odd = 0
    # Write your code here
    for i in range(len(A)):
        if A[i]%2==0:
            even = even + A[i]
        else:
            odd = odd + A[i]
    diff = even - odd

    return diff

Write a program to print sum of elements of the input array A of size N.

Note: User is supposed to write a program from scratch to add the elements of the input array and print the result.

In [ ]:
word = "Scaler Data Science Course"
word_list = list(word)
print(word_list[7:19])

['D', 'a', 't', 'a', ' ', 'S', 'c', 'i', 'e', 'n', 'c', 'e']


In [ ]:
R = int(input())
for  i in range(R):
  if

In [ ]:
x = [1,2,3,4,5,6]
x[::-2]


[6, 4, 2]

Matrix


In [ ]:
m1 = [[23,24,25],
      [67,68,69],
      [45,46,47]]
m1

[[23, 24, 25], [67, 68, 69], [45, 46, 47]]

In [ ]:
#Get 1st row and 3rd column
m1[0][2]

25

In [ ]:
for i in m1:
  print(i)

[23, 24, 25]
[67, 68, 69]
[45, 46, 47]


In [ ]:
for i in range(len(m1)):
  print(m1[i])

[23, 24, 25]
[67, 68, 69]
[45, 46, 47]


In [ ]:
for i in range(len(m1)):
  for j in range(len(m1[0])):
    print(m1[i][j], end = " ")
  print()

23 24 25 
67 68 69 
45 46 47 


Add two matrices

In [ ]:
def addMatrices(A, B):

    #Your Code Goes Here
    M =[]
    for i in range(len(A)):
        row = []
        for j in range(len(A[i])):
            row.append(A[i][j]+B[i][j])
        M.append(row)
    for row in M:
      print(row)



In [ ]:
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

B = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]

addMatrices(A,B)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [ ]:
A = [1,2,3]
max(A)

3

Problem Description

Write a program to input N numbers array, a number X and a number Y from user and insert an element Y in it at specified position X. X is based on 1-based indexing

Note: When an element is inserted at position X, all elements that were already present at position >= X, gets shifted to one position right, not replaced.

Problem Constraints

1 <= N <= 100

1 <= A[i] <= 1000

1 <= X <= N

1 <= Y <= 1000

Input Format

First line is N which represents number of elements.

The next N lines contains an integer.

Third line is X position where Y has to be inserted.

Fourth line is Y which is the value to be inserted.

Output Format

N+1 space separated integers of the input array after inserting the element at required position.

In [ ]:
N = int(input())
Ar = []
n = 0
for n in range(N):
    Ar.append(int(input()))
X = int(input())
Y = int(input())
Ar.insert(X-1,Y)
for i in range(len(Ar)):
    print(Ar[i], end = " ")

4
5
6
5
6
9
2
5 6 5 6 2 

Problem Description

Write a program that reads an integer array A from input and modifies the array by shifting each element to the right by one position and by shifting the last element to the first position. Return the modified array.

Problem Constraints

1 <= N <= 105
1 <= A[i] <= 109
Input Format

The first line of the input is the size of the array N.
The next N lines of the input is integer of the array.

In [ ]:
def shift():
    N = int(input())
    # YOUR CODE GOES HERE
    A = []
    n = 0
    for n in range(N):
        A.append(int(input()))
    A.insert(0,A[-1])
    A.pop()
    return A

Q3. Print in Reverse New

Problem Description

Write a program to print the input array A of size N in reverse order where you have to take integer N and further N elements as input from user.


Problem Constraints

1 <= N <= 1000
1 <= A <= 1000
Input Format

The first line of the input is the size of the array N.
The next N lines of the input is integer of the array.

Output Format

A single line containing N space separated integers representing elements of the input array in reverse order.
Note - Keep a space character (' ') at the end of the line.

In [ ]:

N = int(input())
A = []
n = 0
for n in range(N):
    A.append(int(input()))
A.reverse()
for i in range(len(A)):
    print(A[i], end = " ")



Q4. Negative Integers New
Problem Description

Write a program to print all negative numbers from input array A of size N. Take integer N and N elements of the array as input from user.


Problem Constraints

1 <= N <= 1000
-1000 <= A <= 1000

Input Format

The first line of the input is the size of the array N.
The next N lines of the input is integer of the array.

Output Format

A single line containing elements from the input array which are negative in the same order.

Note - Keep a space character (' ') at the end of the line.

In [ ]:
# Your Code Goes Here
N = int(input())
A = []
n = 0
for n in range(N):
    A.append(int(input()))
for i in range(len(A)):
    if A[i] < 0:
        print(A[i], end = " ")



Q7. Inverse of the Array II
Problem Description

You are given an integer array A. Now your task is to find the inverse of A.
Now, the inverse of the array is A will be an array in which we change the
positions of the values as their indices and indices as values.

So, array A = [2, 0, 1]
- Now 2 is at index 0. So, place 0 at index 2.
- 0 is at index 1. So, place 1 at index 0.
- 1 is at index 2. So, place 2 at index 1.

So, the inverse of A will be [1, 2, 0]
Note: The integer array A is already passed as an argument to the function. User don't need to take any input. Just perform the task on the passed arguments and return the required result.

In [ ]:
def invert(A):
    # Your Code Goes Here
    Ai=[0]*len(A)
    for i in range(len(A)):
        Ai[A[i]] = i
    return Ai

Q8. Matrix Transpose II
Problem Description

Given a 2D integer array A, return the transpose of A.

The transpose of a matrix is the matrix flipped over its main diagonal, switching the matrix's row and column indices.
Note: The 2D integer array A is already passed as an argument to the function. User don't need to take any input. Just perform the task on the passed arguments and return the required result.

In [ ]:
def transpose(A):
    #Your Code Goes Here
    At = []
    for i in range(len(A[0])):
        Atr=[]
        for j in range(len(A)):
            Atr.append(A[j][i])
        At.append(Atr)
    return At

Q9. Matrix Column Sum
You are given input as a square NxN matrix, complete the column_sum function so that it returns the sum of each column as a list.

In [ ]:
def column_sum(matrix):
  # write your code here
  list = []
  for j in range(len(matrix[0])):
      sum = 0
      for i in range(len(matrix)):
          sum = sum + matrix[i][j]
      list.append(sum)
  return list


Q10. Product of elements
Problem Description:

Write a program that returns the product of all elements present in the array.

Note: The list with elements is already passed as an argument to the function. User don't need to take any input. Just perform the task on the passed arguments and return the required result.

In [ ]:
def product(lst):
    ''' input:lst-List of elements in integer format
         output:Return the product as result.'''

    result = 1
    # YOUR CODE GOES HERE
    for  i in lst:
        result *= i

    return result

# STRINGS

Q1. Date formatting
Problem Description:

Given the input date in DD/MM/YYYY format as a string, write a function that returns the converted date in the string formats MM/DD/YYYY and YYYY/MM/DD and return the new date formats.

Input Format:

First input line will have the number of test cases. There will be a single line of input for each
testcase which will consist of date in the string format DD/MM/YYYY.
Output Format:

Resultant date formats in string formats MM/DD/YYYY and YYYY/MM/DD

In [ ]:
def date_format(date):
    '''Input: date takes the string as input
       Output:return resultant date formats'''
    d = date.split("/")
    result1 = "/".join([d[1],d[0],d[2]])
    result2 = "/".join([d[2],d[1],d[0]])
    return result1,result2

date_format("01/01/2020")

('01/01/2020', '2020/01/01')

Problem Description

You are given a character string A and two integer ASCII codes B and C.

You have to find and replace all the occurrences of the character having ASCII code equal to B with character having ASCII code equal to C and return the resultant string.
Input Format

First argument is a character string A.

Second argument is an integer B.

Third argument is an integer C.



Output Format

Return the resultant string after replacing the character(s).



Example Input

Input 1:

 A = "aabbccbb"
 B = 98
 C = 100

 Example Output

Output 1:

 aaddccdd

 Explanation 1:

 Character having ASCII code equal to 98 = 'b'
 Character having ASCII code equal to 100 = 'd'
 Character 'b' occurs at positions 3, 4, 7 and 8 in "aabbaabb".
 After replacing the characters, string becomes "aaddaadd".

In [ ]:
class Solution:
    def solve(self, A, B, C):
        Ar = list(A)
        for i in range(len(Ar)):
            if Ar[i] == chr(B):
                Ar[i] = chr(C)
        result = "".join(Ar)
        return result


'b'

In [ ]:
word = "Scaler Academy"
n = len(word)
n

14

Problem Description

You are given lowercase string (A) and you have to tell the count of vowels and consonants in it.

Input 2:

scaler

Output 2:

[2 4]

In [ ]:
class Solution:
    def solve(self, A):
        v = 0
        c = 0
        for  i in A:
            if i in ('a','e','i','o','u'):
                v += 1
            else:
                c += 1
        return v,c

In [ ]:
 s = "hello"
print( s[: : -1] )

olleh


In [ ]:
a = "Random String"
d = a[:]
d

'Random String'

## **TUPLES and SETS**

Q1. Divide the tuple
Problem Description:

Write a program to divide a given tuple into two tuples that contain even and odd indexed elements of the original tuple. Print both these tuples in the given output format.

Note: The input tuple follows 1-based indexing. This means the element at index 0 is treated as having index as 1.

For example, (9,2,3). The 1-based index of 2 is 2.

Input Format:

The input contains a tuple as an argument to the function.
Output Format:

Print two tuples one for odd indexed elements and another for even indexed elements in the following format:
Odd: (....)
Even: (....)
Sample Input:

1
(10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
Sample Output:

Odd: (10, 5, 10, 10, 5, 8)
Even: (8, 2, 15, 8, 8, 2)

In [ ]:
t = (10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
type(t)

tuple

In [ ]:
t[1]

8

In [ ]:
def odd_even_split_tuple(tup):
    ''' input:tup-indicates the tuple
         output:print two tuples one for even indexed and odd indexed in the given output format'''
    odd = ()
    even = ()
    for i in range(len(tup)):
        if (i+1)%2 == 0:       # Checks the index if its odd or even
            even += (tup[i],)  # Add elements to the tuple
        else:
            odd += (tup[i],)
    print(f"Odd: {odd}")       ## f formatting for string Interpolation
    print(f"Even: {even}")

Q2. Adding to a tuple
Predict the output of the following code as we are trying to append to an immutable tuple:

In [ ]:
name_lst = ["Vijay", "Vickey"]
tup = ("Item_1", 0.5, name_lst)
name_lst.append("Vishal")
print(tup)

('Item_1', 0.5, ['Vijay', 'Vickey', 'Vishal'])


Q4. Length of unique words

Problem Description:

Given two sentences, write a program to return the sum of the total number of unique words from each sentence.

Input Format:

The first line indicates the number of test cases.There will be two lines of inputs for each test cases as following:
The two lines consist of two sentences in string format.

If a word is present in both sentences it should be counted separately for both sentences.

In [ ]:
def set_operation(sent1,sent2):
    ''' input:sent1,sent2-two sentences taken as inputs
         output:return the sum of length of unique words.'''

    # YOUR CODE GOES HERE
    print(len(set(sent1.split(" "))) + len(set(sent2.split(" "))))


In [ ]:
set1 = {1, 2, 4}
set2 = {4, 5, 6}
print(len(set1 | set2))

5


Q6. Symmetric difference
Problem Description

Write a program that returns the symmetric difference of two sets, without actually using the symmetric difference operator.
Example Input

1
10 20 30 40
30 40 50 60
Example Output

{10, 20, 50 ,60}

In [ ]:
def symm_diff(set1, set2 ):
    ''' input:set1,set2-two sets
        output:return symmetric difference set
    '''

    # YOUR CODE GOES HERE
    return (set1 | set2) - (set1 & set2)

Q1. Making Sets
Which of the options defines a set s consisting of strings 'Scaler', 'Academy', 'is', and 'Awesome'?

In [ ]:
s = set(['Scaler', 'Academy', 'is', 'Awesome'])
s

{'Academy', 'Awesome', 'Scaler', 'is'}

In [ ]:
s = set('Scaler', 'Academy', 'is', 'Awesome')
s

TypeError: set expected at most 1 argument, got 4

In [ ]:
s = set('Scaler Academy is Awesome')
s

{' ', 'A', 'S', 'a', 'c', 'd', 'e', 'i', 'l', 'm', 'o', 'r', 's', 'w', 'y'}

In [ ]:

s ={'Scaler', 'Academy', 'is', 'Awesome'}
s

{'Academy', 'Awesome', 'Scaler', 'is'}

Q2. Updating Elements
Complete the code snippet with possible statements from options so that the expected output is obtained.

sets = {3, 4, 5}
___________
print(sets)
Expected Output: {1, 2, 3, 4, 5}

In [ ]:
sets = {3, 4, 5}
sets.update([1, 2, 3])
print(sets)

{1, 2, 3, 4, 5}


In [ ]:
sets = {3, 4, 5}
sets.add(1)
print(sets)

{1, 3, 4, 5}


In [ ]:
sets = {3, 4, 5}
sets += {1}
print(sets)

TypeError: unsupported operand type(s) for +=: 'set' and 'set'

In [ ]:
sets = {3, 4, 5}
sets += {1, 2, 3}
print(sets)

TypeError: unsupported operand type(s) for +=: 'set' and 'set'

In [ ]:
sets = {3, 4, 5}
sets = sets.union({1, 2, 3})
print(sets)

{1, 2, 3, 4, 5}


Q4. Frequency of unique elements
Problem Description:

Write a function to print out the frequency of all the unique elements present in a given tuple.
Sample Input 1:

(10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
Sample Output 1:

10 : 3
8 : 4
5 : 2
2 : 2
15 : 1

In [ ]:
tup = (10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
for i in range(len(tup)):
  print(f"{tup[i]}:{tup.count(tup[i])}")

10:3
8:4
5:2
2:2
10:3
15:1
10:3
8:4
5:2
8:4
8:4
2:2


In [ ]:
def unique_count(tup):
    ''' input:tup-indicates the tuple
         output:Print the unique elements and their frequency'''

    # YOUR CODE GOES HERE
    for i in range(len(tup)):
        if tup[i] not in tup[:i]:
            print(f"{tup[i]} : {tup.count(tup[i])}")

Q5. Access Tuples

In [ ]:
elements = (10, 20, 30, 40, 50, 60, 70, 80)
print(elements[2:5], elements[:4], elements[3:100])

(30, 40, 50) (10, 20, 30, 40) (40, 50, 60, 70, 80)


## **Dictionary**

Q1. Frequency of Characters
Problem Description:

Given an input string, write a program to count the frequency of each character in the string. Map the characters and their respective frequency into a dictionary and return that dictionary.

Note: In the back-end, we are just checking the items in the dictionary, not the order therefore True will be printed if the returned dictionary has the same items as expected otherwise False will be printed.

Sample Input:

ABC
Sample Output:

{'A': 1, 'B': 1, 'C': 1}

In [ ]:
def dict_freq(str1):
    '''str1 is a string
       Ouput -> A dictionary is expected to be returned'''

    # YOUR CODE GOES HERE
    d = {}
    for i in str1:
        if i in d:
            d[i] += 1
        else:
            d[i] = 1
    return d

In [ ]:
string = "abc"
result = {}
for i in set(string):
    result[i] = string.count(i)
result

{'a': 1, 'c': 1, 'b': 1}

Problem Description:

Given a dictionary, find the sum of values of every key in the dictionary.

Input Format:

The input contains two lines.
The first line has space-separated string values which are the keys of the dictionary.
The second line has space-separated integer numbers which are the values of the dictionary.
Output Format:

Print the sum of the values of the items as an integer.
Sample Input:

x y z
25 25 50
Sample Output:

100

The returnSum function is defined with a parameter dict.
The variable sum is initialized to 0. This variable will store the sum of all values in the dictionary.
A for loop is used to iterate over the values in the dictionary using the dict.values() method (for i in dict.values():).
Inside the loop, each value i is added to the sum variable (sum = sum + i).
After the loop, the value of sum is printed using the print function

In [ ]:
def returnSum(dict):
    sum = 0
    # dict.values() will have all the values of dictionary
    for i in dict.values():
          sum = sum + i
    print(sum)

Q6. Least frequent from back
You are given a string of characters, these characters can be anything from alphabets to symbols. Your task is to complete the given function so that it returns the last character that repeated the least times in string. If no such character is present then it should return None

In [ ]:
# write your code here
def count_char(string):
    hash = {}
    for ch in string[::-1]:
        if hash.get(ch, None) != None:
            hash[ch] += 1
        else:
            hash[ch] = 1

    least_freq = (None, float("inf"))
    for ch, freq in hash.items():
        if hash[ch] < least_freq[1]:
            least_freq = (ch, hash[ch])

    return least_freq[0]

Q2. Playing with Keys


In [ ]:
abc = {}
abc[1] = 1
abc
abc['1'] = 2
abc

{1: 1, '1': 2}

Q3. List to dict
You are given a function that takes two lists as input named keys and values respectfully. Return the dictionary such that ith index element of key list have the corresponding ith index element of values list as value.

Note: Lengths of lists maybe different, in that case ignore the extra elements in any list.

Input Format

list[int]
list[int]
Output Format

dict

In [ ]:
def list_to_dict(keys, values):
    # write your code here
    d = {}
    for i in range(min(len(keys),len(values))):   # takes the shorter length
        d[keys[i]] = values[i]
    return d

prices = {'apple': 1.50, 'banana': 0.75, 'orange': 1.25}.

In [ ]:
prices = {'apple': 1.50, 'banana': 0.75, 'orange': 1.25}
prices.pop('banana')
prices

{'apple': 1.5, 'orange': 1.25}

Help on class dict in module builtins:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Built-in subclasses:
 |      StgDict
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |  

In [ ]:
T = int(input())
    for t in range(T):
      A = int(input())

      S = str(A)
      sum = 0
      for i in S:
        sum += int(i)
        print(sum)

3
123
1234
12345
1
3
6
10
15


In [ ]:
num = int(input())
while num > 1:
    num = num // 3
print(num)

72
0


### **Pyhton part 2**

Time and Space Complexity


In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace

In [ ]:
np.arange(22,71,2)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [ ]:
a = np.arange(10)
print(a)
print(a[0])
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
0
[2 3 4]


In [ ]:
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])
print(a.transpose()[-2,-2])

56


In [ ]:
arr = array([10, 12, 15, 17, 2, 5, 4, 6])

NameError: name 'array' is not defined

In [ ]:
import numpy as np
def ratio(marks_arr):
    # Complete the missing code
    marks_arr = np.array(marks_arr)
    distinction = (marks_arr >= 80) # Use masking to get the values
    first_div = (marks_arr >= 60) & (marks_arr < 80) # Use masking to get the values

    distinction_count = np.sum(distinction)
    first_div_count = np.sum(first_div)

    ratio = distinction_count/first_div_count

    return round(ratio,2)

ratio([20, 35, 68, 82, 83, 70, 90])

np.float64(1.5)

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5,6])
a
a[::-1]

array([6, 5, 4, 3, 2, 1])

In [ ]:
a.shape

(6,)

In [ ]:
b = a.reshape(2,3)

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b[:, ::-1]## reversed columns(elements in each row is reversed)


array([[3, 2, 1],
       [6, 5, 4]])

In [ ]:
b[::-1, :]## reversed rows(elements in each column is reversed)

array([[4, 5, 6],
       [1, 2, 3]])